dataset: 'own'
data_folder: "own_skeletons"
output_folder: "output_folder"
prior_folder: 'priors'
model_folder: 'models'
result_folder: 'results'
gender: "neutral"
model_type: 'smplx'
use_cuda: True
gpu_id: 0
float_dtype: "float32"
use_joints_conf: False
use_pca: True
use_hands: False
use_face: False
flat_hand_mean: False
num_gaussians: 8
body_prior_type: 'l2'
left_hand_prior_type: l2
right_hand_prior_type: l2
jaw_prior_type: 'l2'
expr_prior_type: 'l2'
shape_prior_type: 'l2'
focal_length: 5000
num_pca_comps: 12
rho: 100
interpenetration: False
df_cone_height: 0.0001
penalize_outside: True
max_collisions: 1280
optim_type: 'lbfgsls'
ftol: 1e-9
gtol: 1e-9
lr: 1.0
maxiters: 10
interactive: True
visualize: False
skeleton_scale: 0.01
skeleton_axis_order:
    - 0
    - 1
    - 2
skeleton_axis_signs:
    - -1.0
    - 1.0
    - 1.0
debug_joint_mapping: False
joints_to_ign:
    - 12
data_weights:
    - 50
    - 50
    - 50
    # - 50
    # - 50
body_pose_prior_weights:
    # - 4.04e1
    - 4.04e1
    - 57.4e-1
    - 4.78e-1
    # - 4.78e-1
coll_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.01
    - 1.0
shape_weights:
    - 1.0e2
    # - 5.0e1
    - 1.0e1
    # - 0.5e1
    - 0.5e1
expr_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
hand_pose_prior_weights:
    - 4.04e1
    - 4.04e1
    - 57.4e-1
    - 4.78e-1
    - 4.78e-1
jaw_pose_prior_weights:
    - 4.04e03,4.04e04,4.04e04
    - 4.04e03,4.04e04,4.04e04
    - 574,5740,5740
    - 47.8,478,478
    - 47.8,478,478
hand_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 2.0
face_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0
use_vposer: True
use_prev_frame_init: True
vposer_ckpt: "vposer_v1_0"
